### ISSUE TITLE
Could not do normal boot. Invalid Kernel. Length

### ISSUE THREAD

**Issue by marcuskaufmann** [TeamWin/android_device_samsung_herolte#2]
Hi,

I am trying to install LineageOS following he instructions on this [site](https://wiki.lineageos.org/devices/herolte/install#installing-a-custom-recovery-using-heimdall).
I am able to flash the latest [image](https://dl.twrp.me/herolte/twrp-3.2.1-1-herolte.img.html) with Heimdall but I can't access the recovery mode after that. The phone just displays something like "Could not do normal boot. Invalid Kernel. Length!". I've already tried the things that people suggest but I can't get it running. Do you have any futher advice?

Device info: 7.0/NRD90M/G930FXXS2DRA9

Thanks in advance

**Comment by marcuskaufmann** [comment]
After cheking and redoing all steps I discovered that the TWRP image I've downloaded before was corrupt. It works now as designed and described.

**Comment by Mohsents** [comment]
hi bro
1_install CF Auto Root on your device
2_Flash firmware 4 files with Pit
3_Install new TWRP 
4_Programm EMMC
